---
build_from:
  aarch64: docker.io/library/alpine:3.22
  amd64: docker.io/library/alpine:3.22
  armhf: docker.io/library/alpine:3.22
  armv7: docker.io/library/alpine:3.22
  i386: docker.io/library/alpine:3.22
args:
  CRYPTOGRAPHY_VERSION: 46.0.2
  CERTBOT_VERSION: 5.1.0
  ACME_VERSION: 5.1.0
  WIREGUARDTOOLS_VERSION: 0.5.3
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
  JEMALLOC_VERSION: 5.3.0
