---
build_from:
  aarch64: docker.io/library/alpine:3.21
  amd64: docker.io/library/alpine:3.21
  armhf: docker.io/library/alpine:3.21
  armv7: docker.io/library/alpine:3.21
  i386: docker.io/library/alpine:3.21
args:
  CRYPTOGRAPHY_VERSION: 44.0.0
  CERTBOT_VERSION: 3.0.1
  ACME_VERSION: 3.0.1
  WIREGUARDTOOLS_VERSION: 0.5.0
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
  JEMALLOC_VERSION: 5.3.0
