name: Pluggie
version: 0.3.9
slug: pluggie
description: Make your device visible! (Pluggie)
url: https://pluggie.net
codenotary: egresh@pluggie.net
image: ghcr.io/tiborgres/docker-pluggie
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
